server:
  port: 8080

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
    env:
      show-values: when-authorized

logging:
  level:
    ai.demo.springagent: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# AI configuration overrides for dev (optional)
ai:
  max-history-tokens: ${AI_MAX_HISTORY_TOKENS:4096}
  chars-per-token: ${AI_CHARS_PER_TOKEN:4}
