server:
  port: 8080

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${AI_MODEL:gpt-5-nano}
          temperature: 0.7

# AI Configuration
ai:
  model: ${AI_MODEL:gpt-5-nano}
  max-history-tokens: ${AI_MAX_HISTORY_TOKENS:4096}
  chars-per-token: ${AI_CHARS_PER_TOKEN:4}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    ai.demo.springagent: DEBUG
