server:
  port: 0

spring:
  ai:
    openai:
      api-key: test-key
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

logging:
  level:
    ai.demo.springagent: DEBUG
    root: WARN